[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [".venv", "data", "logs"]

[tool.ruff.lint]
select = [
  "E", "F",  # pycodestyle/pyflakes
  "I",        # isort
]
ignore = []

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
disallow_untyped_defs = false
exclude = [".venv", "data", "logs"]
