[theme]
primaryColor = "#eaeaea"
backgroundColor = "#0b0b0b"
secondaryBackgroundColor = "#141414"
textColor = "#eaeaea"
font = "sans serif"
base = "dark"

[server]
headless = true

[client]
toolbarMode = "minimal"
